# this is a generated file, to avoid over-writing it just delete this comment
begin
  require 'jar_dependencies'
rescue LoadError
  require 'com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar'
  require 'com/google/code/gson/gson/2.7/gson-2.7.jar'
  require 'net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar'
  require 'io/airlift/aircompressor/0.16/aircompressor-0.16.jar'
  require 'com/google/protobuf/protobuf-java/3.5.1/protobuf-java-3.5.1.jar'
  require 'com/google/guava/guava/19.0/guava-19.0.jar'
  require 'org/checkerframework/checker-qual/2.0.0/checker-qual-2.0.0.jar'
  require 'com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar'
  require 'com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.jar'
  require 'org/apache/pulsar/pulsar-client-api/2.6.1/pulsar-client-api-2.6.1.jar'
  require 'org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar'
  require 'javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar'
  require 'org/apache/pulsar/pulsar-client/2.6.1/pulsar-client-2.6.1.jar'
  require 'org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar'
  require 'org/apache/pulsar/protobuf-shaded/2.1.0-incubating/protobuf-shaded-2.1.0-incubating.jar'
  require 'org/apache/pulsar/bouncy-castle-bc-shaded/2.6.1/bouncy-castle-bc-shaded-2.6.1.jar'
  require 'javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar'
  require 'com/google/protobuf/protobuf-java-util/3.5.1/protobuf-java-util-3.5.1.jar'
  require 'org/apache/pulsar/pulsar-transaction-common/2.6.1/pulsar-transaction-common-2.6.1.jar'
  require 'com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar'
end

if defined? Jars
  require_jar 'com.google.code.findbugs', 'jsr305', '3.0.2'
  require_jar 'com.google.code.gson', 'gson', '2.7'
  require_jar 'net.jcip', 'jcip-annotations', '1.0'
  require_jar 'io.airlift', 'aircompressor', '0.16'
  require_jar 'com.google.protobuf', 'protobuf-java', '3.5.1'
  require_jar 'com.google.guava', 'guava', '19.0'
  require_jar 'org.checkerframework', 'checker-qual', '2.0.0'
  require_jar 'com.google.j2objc', 'j2objc-annotations', '1.1'
  require_jar 'com.sun.activation', 'javax.activation', '1.2.0'
  require_jar 'org.apache.pulsar', 'pulsar-client-api', '2.6.1'
  require_jar 'org.codehaus.mojo', 'animal-sniffer-annotations', '1.14'
  require_jar 'javax.ws.rs', 'javax.ws.rs-api', '2.1'
  require_jar 'org.apache.pulsar', 'pulsar-client', '2.6.1'
  require_jar 'org.slf4j', 'slf4j-api', '1.7.25'
  require_jar 'org.apache.pulsar', 'protobuf-shaded', '2.1.0-incubating'
  require_jar 'org.apache.pulsar', 'bouncy-castle-bc-shaded', '2.6.1'
  require_jar 'javax.validation', 'validation-api', '1.1.0.Final'
  require_jar 'com.google.protobuf', 'protobuf-java-util', '3.5.1'
  require_jar 'org.apache.pulsar', 'pulsar-transaction-common', '2.6.1'
  require_jar 'com.google.errorprone', 'error_prone_annotations', '2.1.3'
end
