# this is a generated file, to avoid over-writing it just delete this comment
begin
  require 'jar_dependencies'
rescue LoadError
  require 'net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar'
  require 'javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar'
  require 'org/codehaus/mojo/animal-sniffer-annotations/1.14/animal-sniffer-annotations-1.14.jar'
  require 'javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar'
  require 'com/fasterxml/jackson/core/jackson-annotations/2.10.0/jackson-annotations-2.10.0.jar'
  require 'org/bouncycastle/bcprov-jdk15on/1.64/bcprov-jdk15on-1.64.jar'
  require 'joda-time/joda-time/2.8.1/joda-time-2.8.1.jar'
  require 'com/amazonaws/aws-java-sdk-sts/1.11.658/aws-java-sdk-sts-1.11.658.jar'
  require 'org/apache/pulsar/protobuf-shaded/2.1.0-incubating/protobuf-shaded-2.1.0-incubating.jar'
  require 'com/yahoo/athenz/athenz-zts-java-client/1.8.38/athenz-zts-java-client-1.8.38.jar'
  require 'com/google/protobuf/protobuf-java-util/3.5.1/protobuf-java-util-3.5.1.jar'
  require 'org/bouncycastle/bcpkix-jdk15on/1.64/bcpkix-jdk15on-1.64.jar'
  require 'com/yahoo/athenz/athenz-zms-core/1.8.38/athenz-zms-core-1.8.38.jar'
  require 'org/kohsuke/libpam4j/1.11/libpam4j-1.11.jar'
  require 'com/yahoo/athenz/athenz-auth-core/1.8.38/athenz-auth-core-1.8.38.jar'
  require 'org/apache/pulsar/pulsar-client-auth-athenz/2.6.1/pulsar-client-auth-athenz-2.6.1.jar'
  require 'io/jsonwebtoken/jjwt/0.9.1/jjwt-0.9.1.jar'
  require 'com/yahoo/rdl/rdl-java/1.5.2/rdl-java-1.5.2.jar'
  require 'com/sun/activation/javax.activation/1.2.0/javax.activation-1.2.0.jar'
  require 'com/amazonaws/aws-java-sdk-core/1.11.658/aws-java-sdk-core-1.11.658.jar'
  require 'javax/activation/javax.activation-api/1.2.0/javax.activation-api-1.2.0.jar'
  require 'com/fasterxml/jackson/core/jackson-databind/2.10.0/jackson-databind-2.10.0.jar'
  require 'javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar'
  require 'commons-codec/commons-codec/1.11/commons-codec-1.11.jar'
  require 'com/fasterxml/jackson/core/jackson-core/2.9.8/jackson-core-2.9.8.jar'
  require 'com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar'
  require 'com/google/guava/guava/25.1-jre/guava-25.1-jre.jar'
  require 'com/amazonaws/jmespath-java/1.11.658/jmespath-java-1.11.658.jar'
  require 'com/google/protobuf/protobuf-java/3.5.1/protobuf-java-3.5.1.jar'
  require 'com/fasterxml/jackson/dataformat/jackson-dataformat-cbor/2.6.7/jackson-dataformat-cbor-2.6.7.jar'
  require 'com/google/j2objc/j2objc-annotations/1.1/j2objc-annotations-1.1.jar'
  require 'net/java/dev/jna/jna/4.5.2/jna-4.5.2.jar'
  require 'org/apache/pulsar/pulsar-transaction-common/2.6.1/pulsar-transaction-common-2.6.1.jar'
  require 'com/yahoo/athenz/athenz-cert-refresher/1.8.38/athenz-cert-refresher-1.8.38.jar'
  require 'com/yahoo/athenz/athenz-zts-core/1.8.38/athenz-zts-core-1.8.38.jar'
  require 'com/google/errorprone/error_prone_annotations/2.1.3/error_prone_annotations-2.1.3.jar'
  require 'com/yahoo/athenz/athenz-client-common/1.8.38/athenz-client-common-1.8.38.jar'
  require 'org/apache/httpcomponents/httpclient/4.5.9/httpclient-4.5.9.jar'
  require 'com/google/code/gson/gson/2.7/gson-2.7.jar'
  require 'org/apache/httpcomponents/httpcore/4.4.11/httpcore-4.4.11.jar'
  require 'io/airlift/aircompressor/0.16/aircompressor-0.16.jar'
  require 'org/checkerframework/checker-qual/2.0.0/checker-qual-2.0.0.jar'
  require 'org/apache/pulsar/pulsar-client-api/2.6.1/pulsar-client-api-2.6.1.jar'
  require 'org/apache/pulsar/pulsar-client/2.6.1/pulsar-client-2.6.1.jar'
  require 'org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar'
  require 'commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar'
  require 'org/apache/pulsar/bouncy-castle-bc-shaded/2.6.1/bouncy-castle-bc-shaded-2.6.1.jar'
  require 'org/apache/commons/commons-lang3/3.6/commons-lang3-3.6.jar'
  require 'software/amazon/ion/ion-java/1.0.2/ion-java-1.0.2.jar'
end

if defined? Jars
  require_jar 'net.jcip', 'jcip-annotations', '1.0'
  require_jar 'javax.xml.bind', 'jaxb-api', '2.3.1'
  require_jar 'org.codehaus.mojo', 'animal-sniffer-annotations', '1.14'
  require_jar 'javax.ws.rs', 'javax.ws.rs-api', '2.1'
  require_jar 'com.fasterxml.jackson.core', 'jackson-annotations', '2.10.0'
  require_jar 'org.bouncycastle', 'bcprov-jdk15on', '1.64'
  require_jar 'joda-time', 'joda-time', '2.8.1'
  require_jar 'com.amazonaws', 'aws-java-sdk-sts', '1.11.658'
  require_jar 'org.apache.pulsar', 'protobuf-shaded', '2.1.0-incubating'
  require_jar 'com.yahoo.athenz', 'athenz-zts-java-client', '1.8.38'
  require_jar 'com.google.protobuf', 'protobuf-java-util', '3.5.1'
  require_jar 'org.bouncycastle', 'bcpkix-jdk15on', '1.64'
  require_jar 'com.yahoo.athenz', 'athenz-zms-core', '1.8.38'
  require_jar 'org.kohsuke', 'libpam4j', '1.11'
  require_jar 'com.yahoo.athenz', 'athenz-auth-core', '1.8.38'
  require_jar 'org.apache.pulsar', 'pulsar-client-auth-athenz', '2.6.1'
  require_jar 'io.jsonwebtoken', 'jjwt', '0.9.1'
  require_jar 'com.yahoo.rdl', 'rdl-java', '1.5.2'
  require_jar 'com.sun.activation', 'javax.activation', '1.2.0'
  require_jar 'com.amazonaws', 'aws-java-sdk-core', '1.11.658'
  require_jar 'javax.activation', 'javax.activation-api', '1.2.0'
  require_jar 'com.fasterxml.jackson.core', 'jackson-databind', '2.10.0'
  require_jar 'javax.validation', 'validation-api', '1.1.0.Final'
  require_jar 'commons-codec', 'commons-codec', '1.11'
  require_jar 'com.fasterxml.jackson.core', 'jackson-core', '2.9.8'
  require_jar 'com.google.code.findbugs', 'jsr305', '3.0.2'
  require_jar 'com.google.guava', 'guava', '25.1-jre'
  require_jar 'com.amazonaws', 'jmespath-java', '1.11.658'
  require_jar 'com.google.protobuf', 'protobuf-java', '3.5.1'
  require_jar 'com.fasterxml.jackson.dataformat', 'jackson-dataformat-cbor', '2.6.7'
  require_jar 'com.google.j2objc', 'j2objc-annotations', '1.1'
  require_jar 'net.java.dev.jna', 'jna', '4.5.2'
  require_jar 'org.apache.pulsar', 'pulsar-transaction-common', '2.6.1'
  require_jar 'com.yahoo.athenz', 'athenz-cert-refresher', '1.8.38'
  require_jar 'com.yahoo.athenz', 'athenz-zts-core', '1.8.38'
  require_jar 'com.google.errorprone', 'error_prone_annotations', '2.1.3'
  require_jar 'com.yahoo.athenz', 'athenz-client-common', '1.8.38'
  require_jar 'org.apache.httpcomponents', 'httpclient', '4.5.9'
  require_jar 'com.google.code.gson', 'gson', '2.7'
  require_jar 'org.apache.httpcomponents', 'httpcore', '4.4.11'
  require_jar 'io.airlift', 'aircompressor', '0.16'
  require_jar 'org.checkerframework', 'checker-qual', '2.0.0'
  require_jar 'org.apache.pulsar', 'pulsar-client-api', '2.6.1'
  require_jar 'org.apache.pulsar', 'pulsar-client', '2.6.1'
  require_jar 'org.slf4j', 'slf4j-api', '1.7.25'
  require_jar 'commons-logging', 'commons-logging', '1.1.3'
  require_jar 'org.apache.pulsar', 'bouncy-castle-bc-shaded', '2.6.1'
  require_jar 'org.apache.commons', 'commons-lang3', '3.6'
  require_jar 'software.amazon.ion', 'ion-java', '1.0.2'
end
